import 'package:scrolltv_frontend_mobile_flutter/modules/tv-player/domain/entities/channel_model.dart';

List<ChannelModel> channelsData = [
  // ChannelModel(id: generateId(), name: 'BBC NEWS', logo: '', url: Uri.parse(''), category: ['Noticias internacionales', 'todos']),
  // ChannelModel(id: generateId(), name: 'ESPN', logo: '', url: Uri.parse(''), category: ['Deportes en vivo', 'todos']),
  // ChannelModel(id: generateId(), name: 'CNN', logo: '', url: Uri.parse(''), category: ['Noticias 24/7', 'todos']),
  // ChannelModel(id: generateId(), name: 'Televisa', logo: '', url: Uri.parse(''), category: ['Entretenimiento', 'todos']),
  // ChannelModel(id: generateId(), name: 'Discovery', logo: '', url: Uri.parse(''), category: ['Documentales', 'todos']),
  // ChannelModel(id: generateId(), name: 'National Geographic', logo: '', url: Uri.parse(''), category: ['Naturaleza', 'todos']),
  // ChannelModel(id: generateId(), name: 'HBO', logo: '', url: Uri.parse(''), category: ['Películas y series', 'todos']),
  // ChannelModel(id: generateId(), name: 'Disney Channel', logo: '', url: Uri.parse(''), category: ['Entretenimiento familiar', 'todos']),
  // ChannelModel(id: generateId(), name: 'MTV', logo: '', url: Uri.parse(''), category: ['Música y entretenimiento', 'todos']),
  // ChannelModel(id: generateId(), name: 'History Channel', logo: '', url: Uri.parse(''), category: ['Historia y documentales', 'todos']),
  // ChannelModel(id: generateId(), name: 'Cartoon Network', logo: '', url: Uri.parse(''), category: ['Animación', 'todos']),
  // ChannelModel(id: generateId(), name: 'Fox Sports', logo: '', url: Uri.parse(''), category: ['Deportes', 'todos']),
  // ChannelModel(id: generateId(), name: 'Animal Planet', logo: '', url: Uri.parse(''), category: ['Mundo animal', 'todos']),
  // ChannelModel(id: generateId(), name: 'AXN', logo: '', url: Uri.parse(''), category: ['Series y películas', 'todos']),
  // ChannelModel(id: generateId(), name: 'Nickelodeon', logo: '', url: Uri.parse(''), category: ['Infantil', 'todos']),
  // ChannelModel(id: generateId(), name: 'Warner Channel', logo: '', url: Uri.parse(''), category: ['Series y películas', 'todos']),
  // ChannelModel(id: generateId(), name: 'Food Network', logo: '', url: Uri.parse(''), category: ['Cocina y gastronomía', 'todos']),
  // ChannelModel(id: generateId(), name: 'Comedy Central', logo: '', url: Uri.parse(''), category: ['Comedia', 'todos']),
  // ChannelModel(id: generateId(), name: 'Universal Channel', logo: '', url: Uri.parse(''), category: ['Entretenimiento variado', 'todos']),
  // ChannelModel(id: generateId(), name: 'Sony Channel', logo: '', url: Uri.parse(''), category: ['Series y películas', 'todos']),
  // ChannelModel(id: generateId(), name: 'Space', logo: '', url: Uri.parse(''), category: ['Ciencia ficción', 'todos']),
  // ChannelModel(id: generateId(), name: 'TNT', logo: '', url: Uri.parse(''), category: ['Películas', 'todos']),
  // ChannelModel(id: generateId(), name: 'Cinemax', logo: '', url: Uri.parse(''), category: ['Cine', 'todos']),
  // ChannelModel(id: generateId(), name: 'TCM', logo: '', url: Uri.parse(''), category: ['Cine clásico', 'todos']),
  // ChannelModel(id: generateId(), name: 'Syfy', logo: '', url: Uri.parse(''), category: ['Ciencia ficción', 'todos']),
  // ChannelModel(id: generateId(), name: 'Paramount Channel', logo: '', url: Uri.parse(''), category: ['Películas', 'todos']),
  // ChannelModel(id: generateId(), name: 'BBC NEWS 2', logo: '', url: Uri.parse(''), category: ['Noticias internacionales', 'todos']),
  // ChannelModel(id: generateId(), name: 'ESPN 2', logo: '', url: Uri.parse(''), category: ['Deportes en vivo', 'todos']),
  // ChannelModel(id: generateId(), name: 'CNN 2', logo: '', url: Uri.parse(''), category: ['Noticias 24/7', 'todos']),
  // ChannelModel(id: generateId(), name: 'Televisa 2', logo: '', url: Uri.parse(''), category: ['Entretenimiento', 'todos']),
  // ChannelModel(id: generateId(), name: 'Discovery 2', logo: '', url: Uri.parse(''), category: ['Documentales', 'todos']),
  // ChannelModel(id: generateId(), name: 'National Geographic 2', logo: '', url: Uri.parse(''), category: ['Naturaleza', 'todos']),
  // ChannelModel(id: generateId(), name: 'HBO 2', logo: '', url: Uri.parse(''), category: ['Películas y series', 'todos']),
  // ChannelModel(id: generateId(), name: 'Disney Channel 2', logo: '', url: Uri.parse(''), category: ['Entretenimiento familiar', 'todos']),
  // ChannelModel(id: generateId(), name: 'MTV 2', logo: '', url: Uri.parse(''), category: ['Música y entretenimiento', 'todos']),
  // ChannelModel(id: generateId(), name: 'History Channel 2', logo: '', url: Uri.parse(''), category: ['Historia y documentales', 'todos']),
  // ChannelModel(id: generateId(), name: 'Cartoon Network 2', logo: '', url: Uri.parse(''), category: ['Animación', 'todos']),
  // ChannelModel(id: generateId(), name: 'Fox Sports 2', logo: '', url: Uri.parse(''), category: ['Deportes', 'todos']),
  // ChannelModel(id: generateId(), name: 'Animal Planet 2', logo: '', url: Uri.parse(''), category: ['Mundo animal', 'todos']),
  // ChannelModel(id: generateId(), name: 'AXN 2', logo: '', url: Uri.parse(''), category: ['Series y películas', 'todos']),
  // ChannelModel(id: generateId(), name: 'Nickelodeon 2', logo: '', url: Uri.parse(''), category: ['Infantil', 'todos']),
  // ChannelModel(id: generateId(), name: 'Warner Channel 2', logo: '', url: Uri.parse(''), category: ['Series y películas', 'todos']),
  // ChannelModel(id: generateId(), name: 'Food Network 2', logo: '', url: Uri.parse(''), category: ['Cocina y gastronomía', 'todos']),
  // ChannelModel(id: generateId(), name: 'Comedy Central 2', logo: '', url: Uri.parse(''), category: ['Comedia', 'todos']),
  // ChannelModel(id: generateId(), name: 'Universal Channel 2', logo: '', url: Uri.parse(''), category: ['Entretenimiento variado', 'todos']),
  // ChannelModel(id: generateId(), name: 'Sony Channel 2', logo: '', url: Uri.parse(''), category: ['Series y películas', 'todos']),
  // ChannelModel(id: generateId(), name: 'Space 2', logo: '', url: Uri.parse(''), category: ['Ciencia ficción', 'todos']),
  // ChannelModel(id: generateId(), name: 'TNT 2', logo: '', url: Uri.parse(''), category: ['Películas', 'todos']),
  // ChannelModel(id: generateId(), name: 'Cinemax 2', logo: '', url: Uri.parse(''), category: ['Cine', 'todos']),
  // ChannelModel(id: generateId(), name: 'TCM 2', logo: '', url: Uri.parse(''), category: ['Cine clásico', 'todos']),
  // ChannelModel(id: generateId(), name: 'Syfy 2', logo: '', url: Uri.parse(''), category: ['Ciencia ficción', 'todos']),
  // ChannelModel(id: generateId(), name: 'Paramount Channel 2', logo: '', url: Uri.parse(''), category: ['Películas', 'todos'])
];
